"""add services and service relations

Revision ID: 0eb40888a175
Revises: d2e7553464c2
Create Date: 2026-01-07 10:37:02.723929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0eb40888a175'
down_revision: Union[str, Sequence[str], None] = 'd2e7553464c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_offerings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('service_techs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('service_offering_map',
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('offering_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['offering_id'], ['service_offerings.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('service_id', 'offering_id')
    )
    op.create_table('service_tech_map',
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('tech_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.ForeignKeyConstraint(['tech_id'], ['service_techs.id'], ),
    sa.PrimaryKeyConstraint('service_id', 'tech_id')
    )
    op.drop_column('services', 'offerings')
    op.drop_column('services', 'tech_stack')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('tech_stack', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('services', sa.Column('offerings', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_table('service_tech_map')
    op.drop_table('service_offering_map')
    op.drop_table('service_techs')
    op.drop_table('service_offerings')
    # ### end Alembic commands ###
