"""add job_details and internship_details tables

Revision ID: 137e806cae77
Revises: 465b55e60799
Create Date: 2026-01-07 20:00:55.969870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '137e806cae77'
down_revision: Union[str, Sequence[str], None] = '465b55e60799'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('internship_details',
    sa.Column('opportunity_id', sa.UUID(), nullable=False),
    sa.Column('duration_months', sa.Integer(), nullable=True),
    sa.Column('stipend', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('opportunity_id')
    )
    op.create_table('job_details',
    sa.Column('opportunity_id', sa.UUID(), nullable=False),
    sa.Column('employment_type', sa.String(), nullable=True),
    sa.Column('salary_range', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('opportunity_id')
    )
    op.drop_column('opportunities', 'duration')
    op.drop_column('opportunities', 'compensation')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunities', sa.Column('compensation', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('opportunities', sa.Column('duration', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_table('job_details')
    op.drop_table('internship_details')
    # ### end Alembic commands ###
