"""add projects and project tech mapping

Revision ID: 465b55e60799
Revises: 0eb40888a175
Create Date: 2026-01-07 16:55:35.714634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '465b55e60799'
down_revision: Union[str, Sequence[str], None] = '0eb40888a175'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_tech_map',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('tech_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tech_id'], ['service_techs.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'tech_id')
    )
    op.drop_column('projects', 'tech_stack')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('tech_stack', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_table('project_tech_map')
    # ### end Alembic commands ###
