"""remove enroll_from_price from services and add to trainings

Revision ID: b192704617c1
Revises: a081603516b0
Create Date: 2026-01-26 20:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b192704617c1'
down_revision: Union[str, Sequence[str], None] = 'a081603516b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Check if column already exists in trainings (for fresh databases it won't)
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    columns = [c['name'] for c in inspector.get_columns('trainings')]
    
    # Add to trainings only if it doesn't exist (for fresh database setup)
    if 'enroll_from_price' not in columns:
        op.add_column('trainings', sa.Column('enroll_from_price', sa.Numeric(precision=10, scale=2), nullable=True))
    
    # Remove from services
    op.drop_column('services', 'enroll_from_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add back to services
    op.add_column('services', sa.Column('enroll_from_price', sa.Numeric(precision=10, scale=2), nullable=True))
    # Remove from trainings
    op.drop_column('trainings', 'enroll_from_price')
    # ### end Alembic commands ###
